name: 🧯🗄️ Backup CodeIgniter 4 Database

on:
  workflow_call:
    inputs:
      backup-path:
        required: true
        type: string
      environment:
        required: true
        type: string

    secrets:
      DB_HOST:
        required: true
      DB_USER:
        required: true
      DB_PASSWORD:
        required: true
      DB_NAME:
        required: true
      FTP_HOST:
        required: true
      FTP_USER:
        required: true
      FTP_PASSWORD:
        required: true

jobs:
  backup:
    runs-on: ubuntu-latest

    environment: ${{ inputs.environment }}

    steps:
      - name: 📦 Create backup dump
        run: |
          set -e

          DAY=$(date +%a)
          WEEK=$(date +%U)
          SLOT=$((10#$WEEK % 2))
          TIMESTAMP=$(date +%Y%m%d-%H%M%S)

          BACKUP_DIR="${DAY}-${SLOT}"
          BACKUP_NAME="db-backup-${TIMESTAMP}.sql"

          mkdir -p "$BACKUP_DIR"

          mysqldump \
            --no-tablespaces \
            --single-transaction \
            --quick \
            -h "${{ secrets.DB_HOST }}" \
            -u "${{ secrets.DB_USER }}" \
            -p"${{ secrets.DB_PASSWORD }}" \
            "${{ secrets.DB_NAME }}" \
            > "${BACKUP_DIR}/${BACKUP_NAME}"

            echo "BACKUP_DIR=${BACKUP_DIR}" >> $GITHUB_ENV
      - name: 📂 Upload backup via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          security: loose
          local-dir: ./${{ env.BACKUP_DIR }}/
          server-dir: ${{ inputs.backup-path }}/${{ env.BACKUP_DIR }}/

