name: 🧯🗄️ Backup CodeIgniter 4 Database

on:
  workflow_call:
    inputs:
      backup_path:
        required: true
        type: string
      environment:
        required: false
        type: string
        default: ""

    secrets:
      DB_HOST:
        required: true
      DB_USER:
        required: true
      DB_PASSWORD:
        required: true
      DB_NAME:
        required: true
      FTP_HOST:
        required: true
      FTP_USER:
        required: true
      FTP_PASSWORD:
        required: true

jobs:
  backup:
    runs-on: ubuntu-latest

    # attach environment only if provided
    environment: ${{ inputs.environment != '' && inputs.environment || null }}

    steps:
      - name: 📦 Create backup dump
        run: |
          TIMESTAMP=$(date +%Y%m%d_%H%M%S)

          mkdir -p backup

          mysqldump \
            -h "${{ secrets.DB_HOST }}" \
            -u "${{ secrets.DB_USER }}" \
            -p"${{ secrets.DB_PASSWORD }}" \
            "${{ secrets.DB_NAME }}" > backup/db_${TIMESTAMP}.sql

      - name: 📂 Upload backup via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          security: loose
          local-dir: ./backup/
          server-dir: ${{ inputs.backup_path }}
